posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('404/', views.page_not_found, name='Error_404'),
    path('500/', views.server_error, name='Error_500'),
    path('', views.index, name='index'),
    path("follow/", views.follow_index, name="follow_index"),
    path('group/<slug:slug>/', views.group_posts, name='blogs'),
    path('new/', views.new_post, name='new_post'),
    # Профайл пользователя
    path('<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path('<str:username>/<int:post_id>/comment', views.add_comment,
         name='add_comment'),
    path("<str:username>/follow/", views.profile_follow, name="profile_follow"),
    path("<str:username>/unfollow/", views.profile_unfollow,
         name="profile_unfollow"),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    path('auth/', include('users.urls')),
    path('about/', include('django.contrib.flatpages.urls')),
    path('about-us/', views.flatpage, {'url': '/about-us/'}, name='about'),
    path('terms/', views.flatpage, {'url': '/terms/'}, name='terms'),
    path('contacts/', views.flatpage, {'url': '/contacts/'}, name='contacts'),
    path('about-spec/', views.flatpage, {'url': '/about-spec/'},
         name='about-spec'),
    path('about-author/', views.flatpage, {'url': '/about-author/'},
         name='about-author'),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts:index')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/card_author.html
<div class="card">
                            <div class="card-body">
                                    <div class="h2">
                                        <!-- Имя автора -->
                                        {{ profile_user.get_full_name }}
                                    </div>
                                    <div class="h3 text-muted">
                                         <!-- username автора -->
                                         @{{ profile_user.get_username }}
                                    </div>
                            </div>
                            <ul class="list-group list-group-flush">
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                            Подписчиков: {{ profile_user.following.count }} <br />
                                            Подписан: {{ profile_user.follower.count }}
                                            </div>
                                    </li>
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                                <!-- Количество записей -->
                                                Записей: {{ user_post_count }}
                                            </div>
                                    </li>
                            </ul>
                    </div>

templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
        <p class="m-0 text-dark text-center "><a href="/about-author/">Об авторе</a> - <a href="/about-spec/">Технологии</a></p>
        <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube</p>
</footer>

templates/includes/menu.html
{% if user.is_authenticated %}
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'posts:index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'posts:follow_index' %}">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %}

templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'posts:index' %}"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: <a class="p-2 text-dark" href="{% url 'posts:profile' username=user.username%}">{{ user.username }}.</a>
        <a class="p-2 text-dark" href="/new">Новая запись</a>
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

templates/includes/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/includes/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

  <!-- Отображение картинки -->
  {% load thumbnail %}
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img" src="{{ im.url }}" />
  {% endthumbnail %}
  <!-- Отображение текста поста -->
  <div class="card-body">
    <p class="card-text">
      <!-- Ссылка на автора через @ -->
      <a name="post_{{ post.id }}" href="{% url 'posts:profile' post.author.username %}">
        <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
      </a>
      {{ post.text|linebreaksbr }}
    </p>

    <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
    {% if post.group %}
    <a class="card-link muted" href="{% url 'posts:blogs' post.group.slug %}">
      <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
    </a>
    {% endif %}

    <!-- Отображение ссылки на комментарии -->
    <div class="d-flex justify-content-between align-items-center">
      <div class="btn-group">
        {% if post.comments.exists %}
        <div>
          Комментариев: {{ post.comments.count }}
        </div>
        {% endif %}
        <a class="btn btn-sm btn-primary" href="{% url 'posts:post' post.author.username post.id %}" role="button">
          Добавить комментарий
        </a>

        <!-- Ссылка на редактирование поста для автора -->
        {% if user == post.author %}
        <a class="btn btn-sm btn-info" href="{% url 'posts:post_edit' post.author.username post.id %}" role="button">
          Редактировать
        </a>
        {% endif %}
      </div>

      <!-- Дата публикации поста -->
      <small class="text-muted">{{ post.pub_date }}</small>
    </div>
  </div>
</div>