posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('404/', views.page_not_found, name='Error_404'),
    path('500/', views.server_error, name='Error_500'),
    path('', views.index, name='index'),
    path("follow/", views.follow_index, name="follow_index"),
    path('group/<slug:slug>/', views.group_posts, name='blogs'),
    path('new/', views.new_post, name='new_post'),
    # Профайл пользователя
    path('<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path(
        '<str:username>/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path('<str:username>/<int:post_id>/comment', views.add_comment,
         name='add_comment'),
    path("<str:username>/follow/", views.profile_follow, name="profile_follow"),
    path("<str:username>/unfollow/", views.profile_unfollow,
         name="profile_unfollow"),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    path('auth/', include('users.urls')),
    path('about/', include('django.contrib.flatpages.urls')),
    path('about-us/', views.flatpage, {'url': '/about-us/'}, name='about'),
    path('terms/', views.flatpage, {'url': '/terms/'}, name='terms'),
    path('contacts/', views.flatpage, {'url': '/contacts/'}, name='contacts'),
    path('about-spec/', views.flatpage, {'url': '/about-spec/'},
         name='about-spec'),
    path('about-author/', views.flatpage, {'url': '/about-author/'},
         name='about-author'),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts:index')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Сообщество',
        help_text='Выберите название сообщества',
    )
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField(max_length=400)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст сообщения',
        help_text='Напишите текст вашего сообщения'
    )
    pub_date = models.DateTimeField("date published", auto_now_add=True,
                                    db_index=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Сообщество',
        help_text='Выберите название сообщества',
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        null=True,
        verbose_name='Изображение',
        help_text='Выберите картинку для загрузки',
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name='Пост',
        help_text='Текст поста',
        on_delete=models.CASCADE,
        related_name="comments",
        blank=True,
        null=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="comments",
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Напишите текст вашего комментария',
        max_length=400,
    )
    created = models.DateTimeField("date created", auto_now_add=True)

    class Meta:
        ordering = ['-created']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_follow')
        ]

posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import (get_list_or_404, get_object_or_404, redirect,
                              render)
from django.urls import reverse
from django.views.decorators.cache import cache_page
from yatube.settings import RECORDS_ON_THE_PAGE

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


@cache_page(20)
def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, RECORDS_ON_THE_PAGE)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    context = {
        "paginator": paginator,
        "page": page
    }
    return render(request, "index.html", context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)

    posts = group.posts.all()
    paginator = Paginator(posts, RECORDS_ON_THE_PAGE)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    context = {
        "paginator": paginator,
        "group": group,
        "page": page
    }
    return render(request, "group.html", context)


@login_required
def new_post(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect(reverse("posts:index"))

    return render(request, "new_post.html", {"form": form})


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = user.posts.all()
    user_post_count = user.posts.all().count()
    paginator = Paginator(posts, RECORDS_ON_THE_PAGE)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    context = {
        "paginator": paginator,
        "profile_user": user,
        "user_post_count": user_post_count,
        "page": page,
    }
    return render(request, "profile.html", context)


def post_view(request, username, post_id):
    post = get_object_or_404(Post, id=post_id,
                             author__username=username)
    user = post.author
    comments = post.comments.all()
    user_post_count = Post.objects.filter(author=user).count()
    form = CommentForm(request.POST or None)
    context = {
        "profile_user": user,
        "user_post_count": user_post_count,
        "post": post,
        "form": form,
        "comments": comments
    }

    return render(request, "post.html", context)

@login_required
def post_edit(request, username, post_id):
    current_user = request.user
    post = get_object_or_404(Post, id=post_id,
                             author__username=username)
    post_author_user = post.author
    if current_user != post_author_user:
        return redirect("posts:index")

    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()
        return redirect(reverse("posts:post", kwargs={"username": username,
                                                      "post_id": post_id}))

    return render(request, "new_post.html", {"form": form,
                                             "action_text": 'Редактировать',
                                             "post": post})


@login_required
def add_comment(request, username, post_id):
    form = CommentForm(request.POST or None)
    post = Post.objects.get(id__exact=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect(reverse("posts:post", kwargs={'username': username,
                                                      'post_id': post.id}))

    return render(request, "comments.html", {"form": form,
                                             "post": post})


def page_not_found(request, exception=None):
    return render(
        request,
        "misc/404.html",
        {"path": request.path},
        status=404
    )


def server_error(request):
    return render(request, "misc/500.html", status=500)


@login_required
def follow_index(request):
    user = request.user
    posts = Post.objects.filter(author__following__user=user)
    paginator = Paginator(posts, RECORDS_ON_THE_PAGE)
    page_number = request.GET.get("page")
    page = paginator.get_page(page_number)
    context = {
        "paginator": paginator,
        "page": page,
        "profile_user": user,
    }
    return render(request, "follow.html", context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(
            user=user,
            author=author,
        )
    return redirect(reverse("posts:profile", kwargs={"username": username}))


@login_required
def profile_unfollow(request, username):
    follow = get_object_or_404(Follow, author__username=username, user=request.user)
    follow.delete()
    return redirect(reverse("posts:profile", kwargs={"username": username}))

templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
        <!-- Загрузка статики -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
        <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    </head>
    <body>
        <main>
            {% include 'includes/nav.html' %}
            <div class="container">
                <h1>{% block header %}The Last Social Media You'll Ever Need{% endblock %}</h1>
                {% block content %}
                <!-- Содержимое страницы -->
                {% endblock content %}
            </div>
        </main>
        {% include 'includes/footer.html' %}
    </body>

</html>

templates/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
    <form method="post" action="{% url 'posts:add_comment' username=post.author post_id=post.id %}">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

<!-- Комментарии -->
{% for item in comments %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'posts:profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %}

templates/group.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group }}{% endblock %}
{% block header %}{{ group }}{% endblock %}
{% block content %}
    <p>
        {{ group.description }}
    </p>
    <div class="container">
                {% for post in page %}
                    {% include "includes/post_item.html" with post=post %}
                {% endfor %}
    </div>
    {% include "includes/paginator.html" %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}The Last Social Media You'll Ever Need{% endblock %}
{% block content %}
<div class="container">
    {% include "includes/menu.html" with index=True %}
           <h1> Последние обновления на сайте</h1>
            <!-- Вывод ленты записей -->
                {% for post in page %}
                  <!-- Вот он, новый include! -->
                    {% include "includes/post_item.html" with post=post %}
                {% endfor %}
    </div>

        <!-- Вывод паджинатора -->
        {% if page.has_other_pages %}
            {% include "includes/paginator.html" with items=page paginator=paginator%}
        {% endif %}
{% endblock %}

templates/new_post.html
{% extends "base.html" %}
{% block title %}{% if action_text %}{{ action_text }}{% else %}Новая{% endif %}  запись{% endblock %}
{% block header %}{% if action_text %}{{ action_text }}{% else %}Добавить{% endif %} запись{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">{% if action_text %}{{ action_text }}{% else %}Добавить{% endif %} запись</div>
                <div class="card-body">
                    {% for error in form.errors %}
                      <div class="alert alert-danger" role="alert">
                         {{ error|escape }}
                     </div>
                    {% endfor %}
                    <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                            <label for="{{ field.id_for_label }}" class="col-md-3 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                            <div class="col-md-8 col-form-">
                                {{ field|addclass:"form-control" }}
                                {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text">{{ field.help_text|safe }}</small>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                    <div class="col-md-8 offset-md-5">
                        <button type="submit" class="btn btn-primary">
                            {% if action_text %}{{ action_text }}{% else %}Добавить{% endif %}
                        </button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/post.html
{% extends "base.html" %}
{% block title %}{{ profile_user.get_full_name }}{% endblock %}
{% block header %}Запись пользователя {{ profile_user.get_full_name }}{% endblock %}
{% block content %}

<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                                {% include "includes/card_author.html" %}

        </div>

        <div class="col-md-9">

            <!-- Пост -->
                <div class="card mb-3 mt-1 shadow-sm">
                    {% load thumbnail %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img" src="{{ im.url }}">
    {% endthumbnail %}
                        <div class="card-body">
                                <p class="card-text">
                                        <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
                                        <a href="/{{ profile_user.get_username }}/"><strong class="d-block text-gray-dark">@{{ profile_user.get_username }}</strong></a>
                                        <!-- Текст поста -->
                                        {{ post.text }}
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group ">
                                                <!-- Ссылка на редактирование, показывается только автору записи -->
                                            {% if user.is_authenticated and profile_user == user%}
                                                <a class="btn btn-sm text-muted" href="/{{ profile_user.get_username }}/{{ post.id }}/edit" role="button">Редактировать</a>
                                            {% endif %}
                                        </div>
                                        <!-- Дата публикации  -->
                                        <small class="text-muted">{{ post.pub_date|date:"d E Y г. h:m" }}</small>
                                </div>
                        </div>
                </div>
            {% include "comments.html" %}
     </div>
    </div>
</main>

{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block title %}{{ profile_user.get_full_name }}{% endblock %}
{% block header %}Профиль пользователя {{ profile_user.get_full_name }}{% endblock %}
{% block content %}

<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                {% include "includes/card_author.html" %}
                <li class="list-group-item">
    {% if profile_user.following.count %}
    <a class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' username=profile_user.username %}" role="button">
            Отписаться
    </a>
    {% else %}
    <a class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' username=profile_user.username %}" role="button">
    Подписаться
    </a>
    {% endif %}
</li>
            </div>

            <div class="col-md-9">
                    <div class="container">
                {% for post in page %}
                    {% include "includes/post_item.html" with post=post %}
                {% endfor %}
                </div>

                <!-- Остальные посты -->

                <!-- Здесь постраничная навигация паджинатора -->
                {% include "includes/paginator.html" %}

     </div>
    </div>
</main>


{% endblock %}